# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20161129_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='feedback',
            field=models.FileField(blank=True, upload_to='collection/feedbacks/userpackage'),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='upload',
            field=models.FileField(blank=True, upload_to='collection/uploads/userpackage'),
        ),
    ]
